import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LayoutClient from "./layout-client";
import { Toaster } from "sonner";
import LoadingSection from "@/components/common/LoadingSection"; // ✅ Import

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "AYALA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <LoadingSection> {/* ✅ Wrap everything inside */}
          <Toaster position="top-right" richColors />
          <LayoutClient>{children}</LayoutClient>
        </LoadingSection>
      </body>
    </html>
  );
}
